TARGET := iphone:clang:latest:14.0
INSTALL_TARGET_PROCESSES = FreeFire
ffhack_FILES = Tweak.x
ffhack_CFLAGS = -fobjc-arc
ffhack_FRAMEWORKS = UIKit Foundation
include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk